In [1]:
import pandas as pd 
import numpy as np

In [2]:
# load all data
train = pd.read_csv('../data/raw/train_values.csv')
labels = pd.read_csv('../data/raw/train_labels.csv')
test = pd.read_csv('../data/raw/test_values.csv')

In [3]:
import pandas as pd


def feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["age_clipped"] = df["age"].clip(0, 100)
    df["age_bin_old"] = (df["age_clipped"] >= 30).astype(int)

    # Building shape
    df["height_per_floor"] = df["height_percentage"] / df["count_floors_pre_eq"]
    df["area_per_floor"] = df["area_percentage"] / df["count_floors_pre_eq"]
    df["volume_proxy"] = df["area_percentage"] * df["height_percentage"]
    df["slenderness"] = df["height_percentage"] / df["area_percentage"]
    df["is_tall"] = (df["count_floors_pre_eq"] >= 4).astype(int)


    # Structure
    df["old_mud_stone"] = (
        df["age_bin_old"] * df["has_superstructure_mud_mortar_stone"]
    )

    # Family
    df["families_per_floor"] = df["count_families"] / df["count_floors_pre_eq"]
    df["families_per_area"] = df["count_families"] / df["area_percentage"]
    df["has_multiple_families"] = (df["count_families"] > 1).astype(int)

    # Risk score composition
    df["vertical_risk"] = df["count_floors_pre_eq"] * df["height_percentage"]
    

    return df

In [4]:
train = feature_engineering(train)

In [5]:
train

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,height_per_floor,area_per_floor,volume_proxy,slenderness,is_tall,old_mud_stone,families_per_floor,families_per_area,has_multiple_families,vertical_risk
0,802906,6,487,12198,2,30,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,1,0.500000,0.166667,0,10
1,28830,8,900,2812,2,10,8,7,o,r,...,3.500000,4.000000,56,0.875000,0,0,0.500000,0.125000,0,14
2,94947,21,363,8973,2,10,5,5,t,r,...,2.500000,2.500000,25,1.000000,0,0,0.500000,0.200000,0,10
3,590882,22,418,10694,2,10,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,0,0.500000,0.166667,0,10
4,201944,11,131,1488,3,30,8,9,t,r,...,3.000000,2.666667,72,1.125000,0,0,0.333333,0.125000,0,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,688636,25,1335,1621,1,55,6,3,n,r,...,3.000000,6.000000,18,0.500000,0,1,1.000000,0.166667,0,3
260597,669485,17,715,2060,2,0,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,0,0.500000,0.166667,0,10
260598,602512,17,51,8163,3,55,6,7,t,r,...,2.333333,2.000000,42,1.166667,0,1,0.333333,0.166667,0,21
260599,151409,26,39,1851,2,10,14,6,t,r,...,3.000000,7.000000,84,0.428571,0,0,0.500000,0.071429,0,12
260600,747594,21,9,9101,3,10,7,6,n,r,...,2.000000,2.333333,42,0.857143,0,0,1.000000,0.428571,1,18

In [6]:
train

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,height_per_floor,area_per_floor,volume_proxy,slenderness,is_tall,old_mud_stone,families_per_floor,families_per_area,has_multiple_families,vertical_risk
0,802906,6,487,12198,2,30,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,1,0.500000,0.166667,0,10
1,28830,8,900,2812,2,10,8,7,o,r,...,3.500000,4.000000,56,0.875000,0,0,0.500000,0.125000,0,14
2,94947,21,363,8973,2,10,5,5,t,r,...,2.500000,2.500000,25,1.000000,0,0,0.500000,0.200000,0,10
3,590882,22,418,10694,2,10,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,0,0.500000,0.166667,0,10
4,201944,11,131,1488,3,30,8,9,t,r,...,3.000000,2.666667,72,1.125000,0,0,0.333333,0.125000,0,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,688636,25,1335,1621,1,55,6,3,n,r,...,3.000000,6.000000,18,0.500000,0,1,1.000000,0.166667,0,3
260597,669485,17,715,2060,2,0,6,5,t,r,...,2.500000,3.000000,30,0.833333,0,0,0.500000,0.166667,0,10
260598,602512,17,51,8163,3,55,6,7,t,r,...,2.333333,2.000000,42,1.166667,0,1,0.333333,0.166667,0,21
260599,151409,26,39,1851,2,10,14,6,t,r,...,3.000000,7.000000,84,0.428571,0,0,0.500000,0.071429,0,12
260600,747594,21,9,9101,3,10,7,6,n,r,...,2.000000,2.333333,42,0.857143,0,0,1.000000,0.428571,1,18

In [7]:
train.isnull().sum().sort_values(ascending=False).head(20)

building_id                               0
geo_level_1_id                            0
geo_level_2_id                            0
geo_level_3_id                            0
count_floors_pre_eq                       0
age                                       0
area_percentage                           0
height_percentage                         0
land_surface_condition                    0
foundation_type                           0
roof_type                                 0
ground_floor_type                         0
other_floor_type                          0
position                                  0
plan_configuration                        0
has_superstructure_adobe_mud              0
has_superstructure_mud_mortar_stone       0
has_superstructure_stone_flag             0
has_superstructure_cement_mortar_stone    0
has_superstructure_mud_mortar_brick       0
dtype: int64

In [8]:
labels = pd.read_csv('../data/raw/train_labels.csv')

In [9]:
train= pd.merge(train, labels, on='building_id')

In [10]:
train.to_csv('../data/preprocecssed/train.csv')

In [11]:
train_preprocessed = pd.read_csv('../data/preprocecssed/train.csv')

In [12]:
train_preprocessed['damage_grade']

0         3
1         2
2         3
3         2
4         3
         ..
260596    2
260597    3
260598    3
260599    2
260600    3
Name: damage_grade, Length: 260601, dtype: int64

In [13]:
train_preprocessed.isna().sum()

Unnamed: 0                                0
building_id                               0
geo_level_1_id                            0
geo_level_2_id                            0
geo_level_3_id                            0
count_floors_pre_eq                       0
age                                       0
area_percentage                           0
height_percentage                         0
land_surface_condition                    0
foundation_type                           0
roof_type                                 0
ground_floor_type                         0
other_floor_type                          0
position                                  0
plan_configuration                        0
has_superstructure_adobe_mud              0
has_superstructure_mud_mortar_stone       0
has_superstructure_stone_flag             0
has_superstructure_cement_mortar_stone    0
has_superstructure_mud_mortar_brick       0
has_superstructure_cement_mortar_brick    0
has_superstructure_timber                 0
has_superstructure_bamboo                 0
has_superstructure_rc_non_engineered      0
has_superstructure_rc_engineered          0
has_superstructure_other                  0
legal_ownership_status                    0
count_families                            0
has_secondary_use                         0
has_secondary_use_agriculture             0
has_secondary_use_hotel                   0
has_secondary_use_rental                  0
has_secondary_use_institution             0
has_secondary_use_school                  0
has_secondary_use_industry                0
has_secondary_use_health_post             0
has_secondary_use_gov_office              0
has_secondary_use_use_police              0
has_secondary_use_other                   0
age_clipped                               0
age_bin_old                               0
height_per_floor                          0
area_per_floor                            0
volume_proxy                              0
slenderness                               0
is_tall                                   0
old_mud_stone                             0
families_per_floor                        0
families_per_area                         0
has_multiple_families                     0
vertical_risk                             0
damage_grade                              0
dtype: int64

In [14]:
print(train['count_floors_pre_eq'].min())
print(train['area_percentage'].min())

1
1

In [15]:
train.groupby('land_surface_condition')['damage_grade'].mean().sort_values()

land_surface_condition
t    2.234170
n    2.251407
o    2.289081
Name: damage_grade, dtype: float64